//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsmackGTAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIKeys
    {
        public int id { get; set; }
        public string service_name { get; set; }
        public string consumer_key { get; set; }
        public string consumer_secret { get; set; }
        public string user_token { get; set; }
        public string user_secret { get; set; }
        public System.DateTime last_update { get; set; }
        public System.DateTime start_date { get; set; }
    }
}
